-- AlterTable
ALTER TABLE "ongoing_quizzes" ALTER COLUMN "totalEarninginNaira" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalEarninginUSDC" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalEarninginUSDT" SET DATA TYPE DOUBLE PRECISION;
